export const menProducts = [
  {
    id: 1,
    producttype: "men",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/m1.jpg"),
  },
  {
    id: 2,
    producttype: "men",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/m2.jpg"),
  },
  {
    id: 3,
    producttype: "men",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/m3.jpg"),
  },
  {
    id: 4,
    producttype: "men",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/m4.jpg"),
  },
  {
    id: 5,
    producttype: "men",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/m5.jpg"),
  },
  {
    id: 6,
    producttype: "men",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/m6.jpg"),
  },
  {
    id: 7,
    producttype: "men",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/m7.jpg"),
  },
  {
    id: 8,
    producttype: "men",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/m8.jpg"),
  },
];
