export const womenProducts = [
  {
    id: 1,
    sale: "",
    producttype: "women",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/w1.jpg"),
  },
  {
    id: 2,
    sale: "-50%",
    producttype: "women",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/w2.jpg"),
  },
  {
    id: 3,
    sale: "",
    producttype: "women",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/w3.jpg"),
  },
  {
    id: 4,
    sale: "",
    producttype: "women",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/w4.jpg"),
  },
  {
    id: 5,
    sale: "",
    producttype: "women",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/w5.jpg"),
  },
  {
    id: 6,
    sale: "",
    producttype: "women",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/w6.jpg"),
  },
  {
    id: 7,
    sale: "",
    producttype: "women",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/w7.jpg"),
  },
  {
    id: 8,
    sale: "",
    producttype: "women",
    name: "Women's tracksuit Q109",
    price: "$ 30.00",
    img: require("../assets/img/w8.jpg"),
  },
];
